<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MaksIT.ClusterConsole.Shared</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaksIT.ClusterConsole.Client\MaksIT.ClusterConsole.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="MaksIT.Core" Version="1.6.8" />
    <PackageReference Include="MaksIT.Results" Version="2.0.4" />
  </ItemGroup>

</Project>
