<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.8.6</Version>
    <Product>Cluster Console</Product>
    <AssemblyTitle>Cluster Console</AssemblyTitle>
    <Company>MaksIT</Company>
  </PropertyGroup>
</Project>
